apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas
  namespace: dev
type: Opaque
data:
  mongodb.uri.accounts: bW9uZ29kYitzcnY6Ly9kZW1vX3VzZXI6RmVsdGFvdWk1ODFAc3RvcmVmcm9udC1jbHVzdGVyLW0wLW9qcWl5LmdjcC5tb25nb2RiLm5ldC9hY2NvdW50cz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  mongodb.uri.fulfillment: bW9uZ29kYitzcnY6Ly9kZW1vX3VzZXI6RmVsdGFvdWk1ODFAc3RvcmVmcm9udC1jbHVzdGVyLW0wLW9qcWl5LmdjcC5tb25nb2RiLm5ldC9mdWxmaWxsbWVudD9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  mongodb.uri.orders: bW9uZ29kYitzcnY6Ly9kZW1vX3VzZXI6RmVsdGFvdWk1ODFAc3RvcmVmcm9udC1jbHVzdGVyLW0wLW9qcWl5LmdjcC5tb25nb2RiLm5ldC9vcmRlcnM/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
