version: '3.2'

services:
  accounts:
    image: bilel/accounts:latest
    # ports:
    # - "8080:8080/tcp"
    depends_on:
    - kafka
    - mongo
    hostname: accounts
    # environment:
    #   LOGGING_LEVEL_ROOT: DEBUG
    networks:
    - kafka-net

  orders:
    image: bilel/orders:latest
    # ports:
    # - "8080:8080/tcp"
    depends_on:
    - kafka
    - mongo
    - eureka
    hostname: orders
    # environment:
    #   LOGGING_LEVEL_ROOT: DEBUG
    networks:
    - kafka-net

  fulfillment:
    image: bilel/fulfillment:latest
    # ports:
    # - "8080:8080/tcp"
    depends_on:
    - kafka
    - mongo
    - eureka
    hostname: fulfillment
    # environment:
    #   LOGGING_LEVEL_ROOT: DEBUG
    networks:
    - kafka-net

networks:
  kafka-net:
    driver: overlay
